name: reusable-workflow
on:
  push:


jobs:
  call-greeting:
    uses: ./.github/workflows/reusable.yaml # ensure resuable workflow and the calling workflow are in the same repository
    with:
      name: "bibek karki"