name: reusable-workflow
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: 'Name to greet'


jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello ${{ inputs.name }} from the reusable workflow!"